### ISSUE TITLE
Change all references of autocmds to use the new lua autocmd api

### ISSUE THREAD

**Issue by ckipp01** [scalameta/nvim-metals#347]
### Task

When 0.7 is release it will contain the new automd api. Using it locally it's much nicer. When 0.7 is released we'll need to change the way we do the autocmds not only inside of `nvim-metals` but also in the doc examples.

- [ ] autocmds in code changed
- [ ] autocmds in docs changes
- [ ] autocmds in examples in discussions changed
