### ISSUE TITLE
Add in more info to `:MetalsInfo`

### ISSUE THREAD

**Issue by ckipp01** [scalameta/nvim-metals#81]
**Task**

It would be great to have more info in here such as where the logs are located, where Metals is installed, and even what version of Java is detected.

- [x] Where is Metals installed?
- [x] Where is the `nvim-metals.log` file?
- [ ] ~What Java Version is being used?~
- [x] What settings are being set?
- [x] lsp.log location from nvim

I don't think putting Java in here is a great idea since if a user is using Metals, sbt, or Bloop, there may actually Java mismatches between what Bloop may have been started with (depending if Metals didn't start it) vs what you have for running Metals.

**Comment by ckipp01** [comment]
I think I'm going to go ahead and close this for now. I hesitate to put the java version in here primarily because it may be misleading. What `java -version` returns may be different than what coursier is using, different than what you may have in your settings, and maybe different than what Bloop is using. So I don't want to risk having the wrong thing displayed. I can revisit this later if there is demand for it.

**Comment by ckipp01** [comment]
Reopening this as there is a couple other things I should add.
